version: '3'

services:
  client:
    build:
      context: ./client/react-podcast-explorer
      dockerfile: ./Dockerfile
    container_name: 'graphql-podcast-explorer-react'
    command: ./node_modules/.bin/react-scripts start
    ports:
      - "3000:3000"
    # Automatically hot reload code changes in the Docker container
    volumes:
      - ./client/react-podcast-explorer/src:/app/src
    depends_on:
      - server

  server:
    build:
      context: ./server/apollo-server-podcast-explorer
      dockerfile: ./Dockerfile
    container_name: 'graphql-podcast-explorer-apollo-server'
    # Automatically hot reload code changes in the Docker container
    # This service will not start until either the mongodb service is available OR thirty seconds have elapsed
    command: sh -c './scripts/wait-for.sh --timeout=30 mongodb:27017 && ./node_modules/.bin/nodemon ./src/index.js -e js,json,graphql'
    ports:
      - "4000:4000"
      - "9229:9229"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: "graphql-podcast-explorer-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    # If you want to persist MongoDB data after a container has been stopped/deleted, uncomment the volumes section
    # volumes:
    #   - ./databases/mongodb/sandbox/data/db:/data/db
    ports:
      - "27017:27017"
